services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gameshop
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./.srv/database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: gameshop
    ports:
      - "8000:80"
    volumes:
      - ./.srv/wordpress:/var/www/html
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini

      - ./mu-plugins/:/var/www/html/wp-content/mu-plugins/
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./themes/:/var/www/html/wp-content/themes/
    depends_on:
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      MYSQL_USERNAME: myuser
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_HOSTS: mysql
    ports:
      - "8181:80"
    depends_on:
      - mysql
    links:
      - mysql 